require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - features/**/*
    - script/**/*
    - vendor/**/*
Layout/LineLength:
  Exclude:
    - 'jekyll-tagories.gemspec'
